import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lang } }) {
  return (
    <html lang="en">
      <body>
        <Header lang={lang} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
